CREATE DATABASE IF NOT EXISTS your_db_name;
USE your_db_name;

CREATE TABLE notes (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(255),
	content TEXT,
	archived BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);