CREATE DATABASE IF NOT EXISTS nama_db_kamu;
USE nama_db_kamu;

CREATE TABLE notes (
	id INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(255),
	content TEXT,
	archived BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);